[moon]: command to run everything (#210)
moon r frontend:dev-all

There was some sort of cycle if i put this in root so i put it in
frontend
```
Error: project_graph::would_cycle                                                                                                                                                                      
                                                                                                                                                                                                       
  × Unable to create project graph, adding a relationship from root to frontend would introduce a cycle.      
```

---------

Co-authored-by: Arushi Bandi <arushibandi@users.noreply.github.com>